Fixes #19 kmm onboarding 1
icerockdev/kmp-codelabs pull request #35
Opened 2021-08-24 06:54 UTC by kramlex

solving problems from the issue

2021-08-25 02:03 UTC, Alex009 commented
@kramlex в коммитах должны быть ссылки на номера issue на github, то есть:
```
#19 refactor by discussion
#19 add JDK annotation + en
#19 the need for a PATH
```

2021-08-25 02:14 UTC, Alex009 requested changes
комменты к английскому варианту оставлены, для русского аналогично поправить надо

2021-08-25 02:14 UTC, Alex009 commented on src/kmm-icerock-onboarding/lesson-1/kmm-icerock-onboarding-1-en.md
> +We take the path to the Android SDK, which we could see earlier in `Welcome Screen` ->` Configure` -> `Default Project Structure` and add it to` ~ / .zshenv` (or to `~/.bash-profile`). We proceed by
не стоит сокращать в вопросах сетапа окружения - четко какую переменную окружения с каким значением надо установить оставь

2021-08-25 02:14 UTC, Alex009 commented on src/kmm-icerock-onboarding/lesson-1/kmm-icerock-onboarding-1-en.md
> +*Attention:* new environment variables will appear only after restarting the terminal session.
в кодлабе доступно форматирование специальное:
```
Negative
: new environment variables will appear only after restarting the terminal session
```
https://github.com/googlecodelabs/tools/tree/main/claat/parser/md

2021-08-25 02:14 UTC, Alex009 commented on src/kmm-icerock-onboarding/lesson-1/kmm-icerock-onboarding-1-en.md
> +For a comfortable work, you can change the Gradle params not only for this project, but for everyone.
для всех проектов на вашем компе. не для всех людей же :)

2021-08-25 02:14 UTC, Alex009 commented on src/kmm-icerock-onboarding/lesson-1/kmm-icerock-onboarding-1-en.md
> +*Note:* Gradle Sync it's a Gradle task, that looks through all your dependencies listed in the `build.gradle`, and tries to download the specified version.
ну не только зависимости качает, еще всю структуру проекта анализирует, какие языки надо включить и прочее - все что надо чтобы IDE начала работать не как текстовый редактор а как IDE с подсветкой кода, подсказками и прочим

2021-08-25 02:14 UTC, Alex009 commented on src/kmm-icerock-onboarding/lesson-1/kmm-icerock-onboarding-1-en.md
> +### Выбор эмулятора
язык не тот. и перенос строки надо перед заголовком

2021-08-25 02:14 UTC, Alex009 commented on src/kmm-icerock-onboarding/lesson-1/kmm-icerock-onboarding-1-en.md
> +To debug Android application / shared code on Android, just put a breakpoint and start android via Debug mode (bug icon).
нет укзания что "отладка андроид приложения и общего кода полностью та же что в обычной андроид разработке"

2021-08-25 03:29 UTC, kramlex commented on src/kmm-icerock-onboarding/lesson-1/kmm-icerock-onboarding-1-en.md
> +We take the path to the Android SDK, which we could see earlier in `Welcome Screen` ->` Configure` -> `Default Project Structure` and add it to` ~ / .zshenv` (or to `~/.bash-profile`). We proceed by
Поправил!

2021-08-25 03:36 UTC, kramlex commented on src/kmm-icerock-onboarding/lesson-1/kmm-icerock-onboarding-1-en.md
> +For a comfortable work, you can change the Gradle params not only for this project, but for everyone.
Исправлено

2021-08-25 03:36 UTC, kramlex commented on src/kmm-icerock-onboarding/lesson-1/kmm-icerock-onboarding-1-en.md
> +*Note:* Gradle Sync it's a Gradle task, that looks through all your dependencies listed in the `build.gradle`, and tries to download the specified version.
Исправлено

2021-08-25 03:40 UTC, kramlex commented on src/kmm-icerock-onboarding/lesson-1/kmm-icerock-onboarding-1-en.md
> +To debug Android application / shared code on Android, just put a breakpoint and start android via Debug mode (bug icon).
Добавлено

2021-08-30 02:11 UTC, Alex009 approved these changes

2021-08-30 02:12 UTC, merged